name: Test Suite with Clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install autoconf-archive clang libelf-dev python3-pexpect python3-psutil libunwind-dev
    - name: permissions
      run: echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: CC=clang CXX=clang++ ./configure --enable-stack-check
    - name: make
      run: make
    - name: make check
      run: make check
      id: check
    - name: diagnostics
      if: failure () && steps.check.outcome == 'failure'
      run: cat tests/test-suite.log
